package hibernate;

import org.junit.Test;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import constants.Constants;

/**
 * Created by Ufuk on 29-05-15.
 */
public class HibernateTest {
    @Test
    public void hibernate_test() {

        ApplicationContext context =
                new ClassPathXmlApplicationContext("hibernateconf.xml");
        UserService userService =
                context.getBean("UserServiceImpl", UserService.class);

        // username is our username which will be used as parameter of insert method
        // and it's generated by a method(generateRandomWord) of an outside module(constants)
        String username = Constants.generateRandomWord();

        User user = new User();
        user.setUsername(username);
        user.setPassword("123456");

        userService.insertUser(user);

        System.out.println("\nUser: " + userService.getUser(username));

        System.out.println("\nAll Users: \n" + userService.getUsers());
    }
}
